### ISSUE TITLE
Should Query.by_key raise an exception instead of return None?

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#29]
Should `Query.by_key` raise an exception instead of return None?

With a single call, I can test if it returned None:

```python
        obj = self.db.query(self.Model).by_key(key)
        if not obj:
            raise NotFound('No object with key {}'.format(key))
```

However, In the below scenario, an exception maybe more reasonable:

```python
mol_keys = ['111', '222']  # from user input

try:
    mols = [db.query(Molecule).by_key(k) for k in mol_keys]
except XXXException:
    raise BadRequest
```

Here is the behavior of arangosh:

```
127.0.0.1:8529@Amidala> db._document('Task/14382999')._key
14382999

127.0.0.1:8529@Amidala> db._document('Task/xxx')._key
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 1202: document not found
!      throw error;
!      ^
stacktrace: ArangoError: document not found
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:95:21)
    at ArangoDatabase._document (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:626:12)
    at <shell command>:1:4
```

**Comment by kashifpk** [comment]
Yes let's do that. We'll have more conforming behavior with arango tools this way.
